name: CI - Build de imagens Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build imagem do backend
        run: docker build -t frase-backend ./backend

      - name: Build imagem do frontend
        run: docker build -t frase-frontend ./frontend
