name: CI/CD - Build e Push das imagens Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend
      - name: Build imagem do backend
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/frase-backend ./backend

      - name: Push imagem do backend
        run: docker push ${{ secrets.DOCKERHUB_USER }}/frase-backend

      # Frontend
      - name: Build imagem do frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/frase-frontend ./frontend

      - name: Push imagem do frontend
        run: docker push ${{ secrets.DOCKERHUB_USER }}/frase-frontend
